<h1>Pogoda w Lublinie</h1>
<?php
     $data = Mage::registry('data');
     echo '<p><strong>Data: </strong>'.$data['measurement_date'].'</p>';
     echo '<p><strong>Godzina: </strong>'.$data['measurement_hour'].'</p>';
     echo '<p><strong>Temperatura: </strong>'.$data['temperature'].'</p>';
     echo '<p><strong>Prędkość wiatru: </strong>'.$data['wind_speed'].'</p>';
     echo '<p><strong>Kierunek wiatru: </strong>'.$data['wind_direction'].'</p>';
     echo '<p><strong>Wilgotność: </strong>'.$data['humidity'].'</p>';
     echo '<p><strong>Suma opadów: </strong>'.$data['rain'].'</p>';
     echo '<p><strong>Ciśnienie: </strong>'.$data['pressure'].'</p>';
?>
